spring.application.name=EmpPulse
server.port=8080
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
server.servlet.session.timeout=7d

app.owner.email=${APP_OWNER_EMAIL:owner@emppulse.com}
app.owner.password=${APP_OWNER_PASSWORD:admin}