CREATE TYPE "theme" AS ENUM (
  'DARK',
  'LIGHT'
);

CREATE TYPE "language" AS ENUM (
  'ENG',
  'UKR'
);

CREATE TYPE "role" AS ENUM (
  'EMPLOYEE',
  'ADMIN',
  'OWNER'
);

CREATE TYPE "leave_type" AS ENUM (
  'SICK',
  'VACATION',
  'PERSONAL'
);

CREATE TYPE "leave_status" AS ENUM (
  'PENDING',
  'REJECTED',
  'APPROVED',
  'CANCELED'
);

CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "surname" varchar NOT NULL,
  "email" text NOT NULL,
  "pass_hash" text NOT NULL,
  "theme" theme NOT NULL,
  "language" language NOT NULL,
  "role" role NOT NULL,
  "is_deleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE "Employee" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "department_id" integer,
  "user_id" integer NOT NULL,
  "default_hours" integer,
  "vacation_balance" integer NOT NULL,
  "date_of_hiring" date NOT NULL
);

CREATE TABLE "Department" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" text UNIQUE NOT NULL,
  "default_hours" integer
);

CREATE TABLE "Admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE "Leave" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "type" leave_type NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "description" text,
  "paid" boolean NOT NULL,
  "employee_id" integer NOT NULL,
  "creation_time" timestamptz NOT NULL,
  "status" leave_status NOT NULL,
  "admin_reviewer_id" integer,
  "edit_time" timestamptz NOT NULL,
  "admin_comment" text,
  "modification_id" integer
);

CREATE TABLE "Logged_Hours" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "employee_id" integer NOT NULL,
  "admin_id" integer NOT NULL,
  "date" date NOT NULL,
  "start" time NOT NULL,
  "end" time NOT NULL,
  "paid" boolean NOT NULL
);

CREATE TABLE "Admin_Department" (
  "admin_id" integer NOT NULL,
  "department_id" integer NOT NULL
);

CREATE TABLE "Default_hours" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "start" time NOT NULL,
  "end" time NOT NULL,
  "paid" boolean NOT NULL,
  "set_id" integer NOT NULL,
  "day_of_week" smallint NOT NULL
);

CREATE TABLE "Default_hours_set" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL
);

CREATE INDEX "Employee_index_0" ON "Employee" ("user_id");

CREATE INDEX "Employee_index_1" ON "Employee" ("department_id");

CREATE INDEX "Leave_index_0" ON "Leave" ("start_date");

CREATE INDEX "Leave_index_1" ON "Leave" ("edit_time");

CREATE INDEX "Leave_index_2" ON "Leave" ("employee_id");

CREATE INDEX "Logged_Hours_index_0" ON "Logged_Hours" ("date");

CREATE INDEX "Logged_Hours_index_1" ON "Logged_Hours" ("employee_id");

CREATE UNIQUE INDEX "Admin_Department_index_0" ON "Admin_Department" ("admin_id", "department_id");

CREATE INDEX "Default_hours_index_0" ON "Default_hours" ("set_id");

COMMENT ON TABLE "Admin_Department" IS 'CPK admin_id department_id';

ALTER TABLE "Employee" ADD CONSTRAINT "fk_Employee_department_id_Department" FOREIGN KEY ("department_id") REFERENCES "Department" ("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Employee" ADD CONSTRAINT "fk_User_id_Employee" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Admin" ADD CONSTRAINT "fk_User_id_Admin" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Admin_Department" ADD CONSTRAINT "fk_Admin_Department_admin_id_Admin" FOREIGN KEY ("admin_id") REFERENCES "Admin" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Admin_Department" ADD CONSTRAINT "fk_Admin_Department_department_id_Department" FOREIGN KEY ("department_id") REFERENCES "Department" ("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Leave" ADD CONSTRAINT "fk_Leave_employee_id_Employee" FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Leave" ADD CONSTRAINT "fk_Leave_admin_reviewer_id_Admin" FOREIGN KEY ("admin_reviewer_id") REFERENCES "Admin" ("id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Logged_Hours" ADD CONSTRAINT "fk_Logged_Hours_employee_id_Employee" FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Logged_Hours" ADD CONSTRAINT "fk_Logged_Hours_admin_id_Admin" FOREIGN KEY ("admin_id") REFERENCES "Admin" ("id") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Default_hours" ADD CONSTRAINT "fk_Default_hours_set_id_Default_hours_set" FOREIGN KEY ("set_id") REFERENCES "Default_hours_set" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Employee" ADD CONSTRAINT "fk_Employee_default_hours_Default_hours_set" FOREIGN KEY ("default_hours") REFERENCES "Default_hours_set" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Department" ADD CONSTRAINT "fk_Department_default_hours_Default_hours_set" FOREIGN KEY ("default_hours") REFERENCES "Default_hours_set" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Leave" ADD CONSTRAINT "fk_Leave_modification_id_Leave" 
FOREIGN KEY ("modification_id") REFERENCES "Leave" ("id") 
ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;


CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);